---
name: Build and register (manually) balenaOS AWS/EC2 AMI
on:
  workflow_dispatch:
    inputs:
      balena_os_version:
        required: false
        type: string

jobs:
  dispatch-import-vm:
    name: call-import-vm
    uses: belodetek/.github/.github/workflows/vmimport.yaml@7190b8f1bed461fb42c3bf7bbbaf9ac32c29c99f # master
    secrets: inherit
    with:
      balena_os_version: ${{ inputs.balena_os_version }}
