---
name: Build and register (manually) balenaOS AWS/EC2 AMI
on:
  workflow_dispatch:
    inputs:
      balena_os_version:
        required: false
        type: string

jobs:
  dispatch-import-vm:
    name: call-import-vm
    uses: belodetek/.github/.github/workflows/vmimport.yaml@3531288836f6c5faeb7bff26efad8fc2cbcf2af3 # master
    secrets: inherit
    with:
      balena_os_version: ${{ inputs.balena_os_version }}
