---
name: Build and register (manually) balenaOS AWS/EC2 AMI
on:
  workflow_dispatch:
    inputs:
      balena_os_version:
        required: false
        type: string

jobs:
  dispatch-import-vm:
    name: call-import-vm
    uses: belodetek/.github/.github/workflows/vmimport.yaml@b4bbe0fee1f6553484af6aa778a1df8b47788e5e # master
    secrets: inherit
    with:
      balena_os_version: ${{ inputs.balena_os_version }}
