---
name: Google Cloud experiments
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  google-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          project_id: savvy-container-267322
          workload_identity_provider: projects/47855944311/locations/global/workloadIdentityPools/github/providers/oidc
          service_account: my-service-account@savvy-container-267322.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2
      - run: |
          set -x

          gcloud auth list

          curl https://admin.googleapis.com/admin/directory/v1/users?customer=C01jv3tsi \
            --header "Authorization: Bearer $(gcloud auth print-access-token)" \
            | jq -r '.users[].id'
