---
name: Google Cloud experiments
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  google-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          project_id: savvy-container-267322
          workload_identity_provider: projects/47855944311/locations/global/workloadIdentityPools/github/providers/oidc
          create_credentials_file: 'true'

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 461.0.0'

      - run: |
          echo 'project_id: ${{ steps.auth.outputs.project_id }}'
          echo 'credentials_file_path: ${{ steps.auth.outputs.credentials_file_path }}'
          echo 'auth_token: ${{ steps.auth.outputs.auth_token }}'

          gcloud info

          gcloud auth list

          gcloud services list
