---
name: Google Cloud experiments
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  google-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/google-github-actions/auth?tab=readme-ov-file#workload-identity-federation-through-a-service-account
      - uses: google-github-actions/auth@v2
        id: auth
        with:
          project_id: savvy-container-267322
          workload_identity_provider: projects/47855944311/locations/global/workloadIdentityPools/github/providers/oidc
          service_account: my-service-account@savvy-container-267322.iam.gserviceaccount.com

      # https://github.com/google-github-actions/setup-gcloud
      - uses: google-github-actions/setup-gcloud@v2

      # (Google Admin) https://admin.google.com/u/1/ac/roles
      # .. create a custom role and assign admin (service_account)
      # (Google Cloud) https://console.cloud.google.com/
      # .. enable APIs: Admin SDK API, IAM Service Account Credentials API
      - run: |
          set -x

          gcloud auth list

          # https://developers.google.com/admin-sdk/directory/reference/rest/v1/users
          curl --fail --silent \
            https://admin.googleapis.com/admin/directory/v1/users?customer=${CUSTOMER} \
            --header "Authorization: Bearer $(gcloud auth print-access-token)" \
            | jq -r '.users[].id'

          # https://developers.google.com/admin-sdk/directory/reference/rest/v1/roleAssignments/list
          curl --fail --silent \
            https://admin.googleapis.com/admin/directory/v1/customer/${CUSTOMER}/roleassignments \
            --header "Authorization: Bearer $(gcloud auth print-access-token)" | jq -r .

          # https://developers.google.com/admin-sdk/directory/reference/rest/v1/roles/list
          curl --fail --silent \
            https://admin.googleapis.com/admin/directory/v1/customer/${CUSTOMER}/roles \
            --header "Authorization: Bearer $(gcloud auth print-access-token)" | jq -r .

        env:
          CUSTOMER: C01jv3tsi
