---
name: secret-agent-bot

on: workflow_dispatch

jobs:
  # https://josh-ops.com/posts/github-apps/
  github-job:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-app-token
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: ${{ vars.APP_ID }}
          # not needed if installed on this current org/repo
          installation_id: ${{ vars.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: test
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: |
          gh secret list --org ${{ github.repository_owner }}
