---
name: secret-agent-bot

on: workflow_dispatch

jobs:
  # https://josh-ops.com/posts/github-apps/
  github-job:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-app-token
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: ${{ vars.APP_ID }}
          # not needed if installed on this current org/repo
          installation_id: ${{ vars.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: list organizational secrets
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: |
          gh secret list --org ${{ github.repository_owner }}

      - uses: tibdex/github-app-token@v1
        id: generate_read_only_pat
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"secrets": "read"}
          repository: ${{ github.repository }}

      - name: rotate repository secret
        env:
          GH_TOKEN: ${{ steps.generate_read_only_pat.outputs.token }}
        run: |
          gh secret set GH_PAT \
            --app actions \
            --body '${{ steps.get_new_pat.outputs.token }}'

      - name: list repository secrets
        env:
          GH_TOKEN: ${{ steps.generate_read_only_pat.outputs.token }}
        run: gh secret list
