---
name: secret-agent-bot

on: workflow_dispatch

jobs:
  # https://josh-ops.com/posts/github-apps/
  job:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-app-token
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: get_installation_token
        with:
          app_id: ${{ vars.APP_ID }}
          # not needed if installed on this current org/repo
          installation_id: ${{ vars.INSTALLATION_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: list organizational secrets
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: |
          gh secret list --org ${{ github.repository_owner }}

      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate_read_only_pat
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: >-
            {"secrets": "read", "members": "read"}
          repository: ${{ github.repository }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: rotate repository secret
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: |
          gh secret set GH_PAT \
            --app actions \
            --body '${{ steps.generate_read_only_pat.outputs.token }}'
