---
name: test

on: workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: use repository secret
        run: |
          set -x

          gh auth status

          gh secret list

          gh api -i /orgs/${{ github.repository_owner }}/members

        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
